language: generic
osx_image: xcode9

script:
- xcodebuild -workspace Example/TABObserverSet.xcworkspace -scheme TABObserverSet-Example -configuration Debug -sdk iphonesimulator -destination 'OS=11.0,name=iPhone 6s' test
