language: objective-c
osx_image: xcode8.2

script:
- xcodebuild -workspace Example/TABObserverSet.xcworkspace -scheme TABObserverSet-Example -configuration Debug -sdk iphonesimulator -destination 'OS=10.0,name=iPhone SE' test
